name: common_utils
description: Dart common utils library.Contain DateUtil, EncryptUtil, JsonUtil, LogUtil, MoneyUtil, NumUtil, ObjectUtil, RegexUtil, TextUtil, TimelineUtil, TimerUtil.
version: 2.0.2
homepage: https://github.com/Sky24n/common_utils

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"

dependencies:
  # https://github.com/a14n/dart-decimal
  decimal: ">=1.0.0 <3.0.0"
  # https://github.com/dart-lang/crypto
  crypto: ">=3.0.0 <5.0.0"
  # https://github.com/dart-lang/convert
  convert: ">=3.0.0 <5.0.0"