name: common_utils
description: Dart common utils library.Contain DateUtil, EncryptUtil, JsonUtil, LogUtil, MoneyUtil, NumUtil, ObjectUtil,  RegexUtil, TextUtil, TimelineUtil, TimerUtil.
version: 1.2.0
author: Sky24n <863764940@qq.com>
homepage: https://github.com/Sky24n/common_utils

environment:
  sdk: ">=1.19.0 <3.0.0"
dependencies:
  # https://github.com/a14n/dart-decimal
  decimal: ">=0.3.1 <2.0.0"
  # https://github.com/dart-lang/crypto
  crypto: ">=2.0.6 <4.0.0"
  # https://github.com/dart-lang/convert
  convert: ">=1.0.0 <4.0.0"