name: common_utils
description: Dart common utils library.Contain DateUtil, EncryptUtil, JsonUtil, LogUtil, MoneyUtil, NumUtil, ObjectUtil, RegexUtil, TextUtil, TimelineUtil, TimerUtil.
version: 2.1.0
homepage: https://github.com/Sky24n/common_utils

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # https://github.com/a14n/dart-decimal
  rational: ">=2.0.0 <5.0.0"
  # https://github.com/a14n/dart-decimal
  decimal: ">=2.0.0 <5.0.0"
  # https://github.com/dart-lang/crypto
  crypto: ">=3.0.0 <5.0.0"
  # https://github.com/dart-lang/convert
  convert: ">=3.0.0 <5.0.0"